config/routes.rb
Rails.application.routes.draw do

  #Espaço do Admin
  namespace :admin do


    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

  devise_for :users, :controllers => { registrations: 'registrations',
                                        :omniauth_callbacks => "callbacks" }



  authenticated :user do
    root 'admin/pages#home', as: :authenticated_root
  end

  #Espaço Público
  controller :pages do
    get '/home' => :home
  	get '/logout' => :logout
  end 

  root 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image
      unless auth.extra.blank? or auth.extra.raw_info.blank?
        user.location = auth.extra.raw_info.location.name unless auth.extra.raw_info.location.blank?
        user.sex = auth.extra.raw_info.gender
      Rails.logger.debug("  ============== # {} My object:  ====== acao: " + "#{auth} ------ #{auth.extra.raw_info.gender}")
      end

    end
  end



  def self.sex_to_select
    [
      "Male.",
      "Female.",
      "I don't wanna say."
    ]
  end


end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	
  before_action :authenticate_user!
  
  layout 'admin'

  def home
  end

  
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController
  def home
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :image)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :current_password, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found


  
  private
    
    def record_not_found
      flash[:alert] = "Record not Found"
      redirect_to root_url
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 
  def facebook 
    @user = User.from_omniauth(request.env["omniauth.auth"]) 
    if @user.persisted? 
      sign_in_and_redirect @user, :event => :authentication
    else
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < PublicController
  def home
    @get_info = params[:data]    
    params[:token].blank? ? (params[:token] = session[:token] unless session[:token].blank?) : nil
    unless params[:token].blank?
      uri = URI("https://api.socialidnow.com/v1/marketing/login/info?api_secret=921c4749711c4c794fb5d75bee1d97349330ca4e535640139b98e66acfee715a&token=#{params[:token]}")
      @net_http = Net::HTTP.get(uri)
      session[:token] = params[:token] unless params[:token].blank?
    end
  end

  def logout
  	session.delete(:token)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  layout 'publico'
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :sex, :location, :description, :email, :password, :password_confirmation, :image)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :sex, :location, :description, :email, :password, :password_confirmation, :current_password, :image)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def liked?(user, post)
    user.likes.find_by(post_id: post.id)
  end
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/home.html.erb
<div class="row">
  <div class="center">
    <h4 class="title brown-text"><%= "Bem-vindo, #{current_user.name}" %></h4>
    </div>
  </div>
</div>

<div class="container">
  <ul class="collection">
    <li class="collection-item avatar">
      <img src="<%= current_user.image %>" class="circle">
      <h1 class="title">Profile</h1>
      <hr>
      <br>
      <p><strong>Name: </strong><%= current_user.name %></p>
      <p><strong>E-mail:</strong> <%= current_user.email %></p>
      <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
      <p><strong>Location: </strong><%= current_user.location %></p>
      <p><strong>Sex:</strong> <%= current_user.sex %></p>
      <p style="text-align: right;">
        <%= link_to('Log Out', destroy_user_session_path, :method => :delete) %>
      </p>
    </li>
  </ul>
</div>

app/views/admin/shared/_navbar.html.erb
<ul id="slide-out" class="side-nav">
    <li><div class="user-view brown">
      <img src="<%= current_user.image %>" class="circle">
      <a href="#"><span class="white-text name"><%= "#{current_user.name}" %></span></a>
      <a href="#"><span class="white-text name"><%= "#{current_user.email}" %></span></a>
      <br>
    </div></li>


              <li><%= link_to 'Profile', admin_root_path %></li>
              <li class="divider"></li>
              <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
  </ul>
  <div style="margin: 15px;">
    <a href="#" data-activates="slide-out" class="btn btn-floating pulse button-collapse brown">
      <i class="material-icons">menu</i>
    </a>
  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Bean - Social ID</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "admin/shared/navbar" %>
    </header>

    <main>
        <div class="col s12 m12 l12 xl12">
          <%= yield %>
        </div>
    </main>

    <footer>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'red')" %>
      <% else message_type == 'notice' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'green')" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Bean - Social ID</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/nav" %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'red')" %>
      <% else message_type == 'notice' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'green')" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/layouts/publico.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Bean - Social ID</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/nav" %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'red')" %>
      <% else message_type == 'notice' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'green')" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/pages/_user_info.html.erb
<% unless @net_http.blank? %>
<div>
    <p> <%= @net_http %> </p>
</div>
<% end %>
<% unless @get_info.blank? %>
  <p> <img src="<%= @get_info['picture_url'] %>"></p> 
  <p> <strong>User ID</strong>: <%= @get_info["user_id"] %></p> 
  <p> <strong>Name</strong>: <%= @get_info["name"] %></p> 
  <p> <strong>E-mail</strong>: <%= @get_info["email"] %></p> 
  <p> <strong>Location</strong>: <%= @get_info["location"] %></p> 
  <p> <strong>Username</strong>: <%= @get_info["username"] %></p> 
<% end %>
<% unless @net_http.blank? and @get_info.blank? %>
  <button id="logout" class="brn brown btn-floating pulse" onclick="logout()">Out</button>
<% end %>


<script type="text/javascript">

 var handler = function(response) {}

 function logout() {
   socialid.login.logout(handler);
   $.ajax({
    url: "/logout",
    method: "GET",
    dataType: "script",
  });

 }
</script>

<style type="text/css">
  p{
    text-align: justify;
  }
</style>

app/views/pages/home.html.erb
<div class="row home">
  <div class="center">
    <h4 class="title">Coffee Bean - Social ID</h4>
    <div style="background: rgba(000,000,000, 0.7); height: auto;">
      <div id="home_paralax" class="parallax-container">
        <div class="parallax">
          <img src="/parallax2.jpg">
        </div>
      </div>
    </div>

    <div id='login-c6ab6f67' style='display: inline-block; padding: 5px'></div>
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <div id="user_info">
          <%= render 'user_info' %>
        </div>
      </div>
    </div>

  </div>
</div>


<script>
  (function() {
    if (typeof(window.socialid) !== "object") window.socialid = {};
    socialid.onLoad = function() {
      socialid.login.init(437, {loginType: "event"});


      socialid.login.getUserInfo(handler, {fields: "display_name,verified_email,current_location,picture_url,providers"});

      socialid.events.onLoginSuccess.addHandler(function(data) {
        login(data.token);
        setTimeout(function(){
           window.location.reload(1);
        }, 1000);
      });

      socialid.login.renderLoginWidget("login-c6ab6f67",
        {"providers":["facebook","gplus","twitter","linkedin"],"theme":"bricks","showSocialIdLink":true},
        );
    };
    var e = document.createElement('script');
    e.type = 'text/javascript';
    e.id = '';
    if (document.location.protocol === 'https:') {
      e.src = 'https://staging.socialidnow.com/assets/api/socialid.js';
    } else {
      e.src = 'http://staging.socialidnow.com/assets/api/socialid.js';
    }
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(e, s);
  })();


</script>




<script type="text/javascript">
  $(document).ready(function(){
    $('.parallax').parallax();
  });
</script>




<script type="text/javascript">

 var handler = function(response) {
  if (response.status == "success") {
    $.ajax({
      url: "/home",
      method: "GET",
      dataType: "script",
      data: {
        'data':         response.data
      },
    });
  } 
}

function login(token){
  $.ajax({
    url: "/home",
    method: "GET",
    dataType: "script",
    data: {
      'token':         token
    },
  });
}

</script>

app/views/pages/home.js.erb
$("#user_info").html("<%= j( render 'user_info' )%>");

app/views/pages/logout.js.erb
$("#user_info").html("<%= j( render 'user_info' )%>");

app/views/shared/_footer.html.erb
<div class="page-footer brown">
  <div class="container">
    <div class="copyright">
      <b>
      <p style="text-align: center;">
       Copyright ® <%= Date.today.year %> | Coffee Bean Social ID | 
      </p>
      </b>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="brown">
  <div class="nav-wrapper">
    <a href="/home.html" class="brand-logo"><i class="material-icons">cloud</i>Coffee Bean</a>
    <ul class="right hide-on-med-and-down" style="display: none;">
    	<% if current_user %>
              <li><%= link_to "#{current_user.name}", admin_root_path %></li>
        <% else %>
			  <li><%= link_to "Login", new_user_session_path %></li>
			  <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
    </ul>
  </div>
</nav>